### ISSUE TITLE
Not working on macOS 15.0

### ISSUE THREAD

**Issue by fedamerd** [zackelia/bclm#56] opened 2024-09-16 19:35 UTC
Just updated my M2 MBP to macOS 15.0 and started getting the following error when running bclm read / write commands:

`keyNotFound(code: "CHWA")`

The previously set value also doesn't seem to apply anymore, as the Mac was charging up to 100% after the update.

**Comment by jlaundry** [comment] 2024-09-16 20:47
Duplicate of #49

**Closed as not planned** 2024-09-16 20:53 UTC
